# v0.1
name: Lock old (and closed) issues

on:
  schedule:
    - cron: '25 1 * * 0'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: Lock old closed issues
        uses: dessant/lock-threads@v6
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '180' # 6 months (approximately)
          issue-lock-reason: 'resolved'
          process-only: 'issues'
          issue-comment: 'This issue has been locked since there has not been any recent activity after it was closed. Please open a new issue if you want to report a problem or suggest a new feature and eventually reference this issue there.'
